### ISSUE TITLE
如何配合后端图片上传接口，使用wangEditor V5 上传图片——自定义上传

### ISSUE THREAD

**Issue by LCG669** [wangeditor-team/wangEditor-v5#450]
## 问题描述

使用wangEditor V5 上传图片——自定义上传
配套环境 Vue3 + TypeScript + Axios
目前已实现：
1. wangEditor V5的文字的增删改查（以此证明接口正常）
2. element plus库的Upload组件的图片的增删改查（以此证明接口正常）

## wangEditor 版本

_"@wangeditor/editor": "^0.14.2"
"@wangeditor/editor-for-vue": "^5.1.8-7"_

## 是否查阅了文档 ？
[浏览了官方文档，链接：https://www.wangeditor.com/v5/guide/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0](https://www.wangeditor.com/v5/guide/menu-config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0)

（文档链接 [doc.wangEditor.com](https://doc.wangeditor.com/) ）

*是*

## 最小成本的复现步骤

（请告诉我们，如何**最快的**复现该问题？）

- 步骤一
后台接口使用springboot实现，接受单个MultipartFile文件类型参数
- 步骤二
根据后台接口文档，前端对应的接口封装文件
```
// upLoad 文件上传 位于 @/network/upLoad

import http from '@/network/http' // http文件是全局的接口封装文件，仅负责配置baseURL地址和挂载token到请求头

export default (data: FormData) => {
  return http({
    url: '/sys/common/localUpload',
    method: 'post',
    data,
    headers: {
      "Content-Type": "multipart/form-data;",
    },
    transformRequest: [
      () => {
        return data;
      }
    ]
  })
}
```
- 步骤三
使用官网示范，[使用Vue3的写法：https://juejin.cn/post/7027977252331585544](https://juejin.cn/post/7027977252331585544)
这是我编写的.vue文件运行代码：
```
<template>
<div>
  <Toolbar
    :editorId="form.editorId"
    :defaultConfig="form.editorConfig"
  />
  <!-- 富文本区域 -->
  <Editor
    :editorId="form.editorId"
    style="width: 380px; height: 500px"
  />
</div>
</template>

<script lang='ts' setup>
import { onBeforeUnmount, ref } from 'vue'
import { useStore } from 'vuex'

import "@wangeditor/editor/dist/css/style.css"
import { Editor, Toolbar, getEditor, removeEditor } from '@wangeditor/editor-for-vue'

import upLoad from '@/network/upLoad'

const store = useStore()

type InsertFnType = (url: string, alt: string, href: string) => void

const form = {
  editorId: 'Build', // 定义一个编辑器 id，全局唯一且不变
  editorConfig: { // 编辑器配置
    excludeKeys: [
      'fullScreen'
    ],
    autoFocus: false,
    MENU_CONF: {
      uploadImage: {
        server: store.state.http + '/sys/common/localUpload',
        maxFileSize: 10 * 1024 * 1024, // 10MB
        meta: {
          token: store.state.token
        },
        headers: {
          "Content-Type": 'multipart/form-data;'
        },
        /** 自定义上传 */
        async customUpload(file: File, insertFn: InsertFnType) {
          // file 即选中的文件
          // 自己实现上传，并得到图片 url alt href
          // 最后插入图片

          // 开始上传文件 新建一个formData
          const formData = new FormData();
          // 通过append向form对象添加数据
          formData.append("file", file);

          upLoad(formData)
          .then(res => {
            console.log('上传成功')
            console.log(res.data.result)
            insertFn(res.data.result, '图片', res.data.result)
          })
        }
      }
    }
  }
}
// 组件销毁时，及时销毁编辑器
onBeforeUnmount(() => {
  const editor = getEditor(form.editorId)
  if (editor == null) return

  // 销毁，并移除 editor
  editor.destroy()
  removeEditor(form.editorId)
})
</script>
```

**Comment by itshizhan** [comment]
自定义上传不需要配置server。
你的` upLoad(formData)` 是什么？
你应该在upLoad 直接上传就可以了。

**Comment by LCG669** [comment]
> 自定义上传不需要配置服务器。 你` upLoad(formData)`是什么？ 你应该在上传直接上传就可以了。

upLoad(formData)就是步骤二的上传方法

**Comment by LCG669** [comment]
> > 自定义上传不需要配置服务器。你` upLoad(formData)`是什么？你应该在直接上传就可以了。
> 
> upLoad(formData)就是步骤二的上传方法

删除或不删除server，都会提示Error: Cannot get upload server address 没有配置上传地址

**Comment by itshizhan** [comment]
自定义上传，直接配置customUpload就可以了。
```
editorConfig.MENU_CONF['uploadImage'] = {
    // 自定义上传
    async customUpload(file: File, insertFn: InsertFnType) {
        console.log(file)
        // 客户端可以判断文件大小、文件类型
        // file 即选中的文件
        // 自己实现上传，并得到图片 url alt href
        // 最后插入图片
        insertFn(url, alt, href)
    }
}
```
你这个错误，应该是客户端报的错误吧。

**Comment by LCG669** [comment]
> 自定义上传，直接配置自定义上传就可以了。
> 
> ```
> editorConfig.MENU_CONF['uploadImage'] = {
>     // 自定义上传
>     async customUpload(file: File, insertFn: InsertFnType) {
>         console.log(file)
>         // 客户端可以判断文件大小、文件类型
>         // file 即选中的文件
>         // 自己实现上传，并得到图片 url alt href
>         // 最后插入图片
>         insertFn(url, alt, href)
>     }
> }
> ```
> 
> 你这个错误，应该是客户端报的错误吧。

customUpload除了console.log(file)以外 全部删除 ，控制台也无法打印消息，仍然报这个错误。
错误完整代码：
```
{
  message:"Cannot get upload server address
  没有配置上传地址"
  stack:"Error: Cannot get upload server address
  没有配置上传地址
      at Object.t.createUploader (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:57:141181)
      at eval (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:128:20935)
      at eval (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:128:21628)
      at eval (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:128:1458)
      at Object.eval [as next] (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:128:1563)
      at eval (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:128:499)
      at new Promise (<anonymous>)
      at yr (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:128:244)
      at du (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:128:20687)
      at eval (webpack-internal:///./node_modules/@wangeditor/editor/dist/index.esm.js:128:22316)"
}
```

**Comment by itshizhan** [comment]
你可以提供的可复现的demo看看
我本地刚测试，没有发现你说的错误

**Comment by wangfupeng1988** [comment]
要解决这个问题，你要先抛开 Vue 的环境，就用最简单的 html demo 去复现问题，不要掺杂任何无关代码。

如复现了，可以把 html 代码提交到这里。

**Comment by wangfupeng1988** [comment]
另外，经过测试，配置了 `customUpload` 之后，就不要再配置 `server` 和 `fieldName` 了。
